Repository sunt-programator/CodeIT, pull requests merged in 2021-01, with the labels that each got.

#74 Add a Table of Contents to the readme
  README.md
Labels: documentation

#79 Fix error on rendering empty posts
  layouts/partials/function/content.html
Labels: bug

#73 Enable the use of HTML within subtitle
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.fr.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  layouts/partials/home/profile.html
Labels: enhancement

#84 feat(avatar): adding alt text
  .devcontainer/devcontainer.json
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.fr.md
  layouts/partials/home/profile.html
Labels: enhancement
